language: node_js
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "8"
  - "10"
  - "12.14.1"

before_install:
  - export CXX="clang-10.0" CC="clang++-10.0"

script:
  - npm run standard
  - npm run test:node
  - npm run test:native

git:
  depth: 10

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-10.0
    - clang++-10.0
